### ISSUE TITLE
git ignore workspace.xml

### ISSUE THREAD

**Issue by aviaryan** [bxute/collegare-app#2]
.idea/workspace.xml changes heavily between commits and thus pollutes the repo diff. 
On an average, it has around 1000 :heavy_plus_sign: :heavy_minus_sign:  in every commit. 

[ [ignoring a tracked file](http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore) ]

**Comment by singhpratyush** [comment]
Removed the directory.
