### ISSUE TITLE
@bxute, fix your git username and email

### ISSUE THREAD

**Issue by aviaryan** [bxute/collegare-app#3]
Some of the commits from @bxute are coming as @ankit460 . [evidence](https://github.com/bxute/collegare-app/commits?author=ankit460)
Please update your git username and email to one used in @bxute account to fix this issue.

**Comment by singhpratyush** [comment]
Will this ever be fixed?

**Comment by aviaryan** [comment]
@bxute | @ankit460 Google may reject you because of this. :laughing:

**Comment by bxute** [comment]
now somehow i fixed it.,,..... thanks for mentioning

**Comment by aviaryan** [comment]
cool
